apiVersion: apps/v1
kind: Deployment
metadata:
  name: sportstadium-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sportstadium-api
  template:
    metadata:
      labels:
        app: sportstadium-api
    spec:
      containers:
        - name: sportstadium-api
          image: sportstadium-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "123456"
            - name: DB_NAME
              value: "sportsdb"
---
apiVersion: v1
kind: Service
metadata:
  name: sportstadium-service
spec:
  type: NodePort
  selector:
    app: sportstadium-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
