apiVersion: v1
kind: Service
metadata:
  name: sportstadium-service
spec:
  type: NodePort
  selector:
    app: sportstadium-api
  ports:
    - name: http
      port: 5003 # 
      targetPort: 5003 
      nodePort: 30080 
